# Generated by Django 5.1.5 on 2025-02-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(editable=False, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('W', 'Ожидание'), ('R', 'Готово'), ('P', ' Оплачено')], max_length=2, verbose_name='Статус')),
                ('items', models.ManyToManyField(to='core.dish')),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.table', verbose_name='Номер стола')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'Order',
            },
        ),
    ]
