# Generated by Django 5.1.5 on 2025-02-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('W', 'Ожидание'), ('R', 'Готово'), ('P', ' Оплачено')], default='W', max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Общая стоимость'),
        ),
    ]
